version: '3.5'

services:

  maven:
    container_name: pnc-maven
    build: 
      context: maven
      network: host
    network_mode: host
    volumes:
      - ./:/usr/src/project
      - ./maven/.m2:/root/.m2
    command: ./run.sh
    
  app:
    container_name: pnc-app
    build: 
      context: app
      network: host
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/api  
    ports:
      - 8080:8080

networks:
  pnc-network:
    driver: bridge